apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-echo-server
  labels:
    app: echo-server
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: echo-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: echo-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: echo-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-listen=:{{ .Values.service.port }}"
            - "-text=hello-bare"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
