{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "echo-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echo-server.labels" . | nindent 4 }}
  annotations:
    kontractor.io/managed: "true"
automountServiceAccountToken: true
{{- end }}
