replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "latest"
  pullPolicy: IfNotPresent

contract:
  features:
    tls: false

echo:
  text: "Hello from Kontractor!"
  port: 5678

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

serviceAccount:
  create: true

rbac:
  create: true

tls:
  secretName: ""
